### ISSUE TITLE
Can't add LV2 plugin in Ardour 6 Flatpak

### ISSUE THREAD

**Issue by ghost** [sfztools/sfizz-ui#36]
It seems like LV2 plugin is found and can be added to the track on Ardour 6, but the plugin isn't visible on the editor mixer section, and the GUI isn't loaded. I tried enabling and disabling the plugin GUIs in Ardour, and still the plugin isn't visible.

I put sfizz.lv2 folder in ~/.lv2 after installation, since I use the flatpak version of Ardour. This might be the cause. I do the same thing with liquidsfz, and the plugin works fine. 

I saw some posts about this on Ardour forums too, but I think this might be a sfizz issue.

Edit: I'm using Ubuntu 22.04 with Ardour latest flatpak version. I installed sfizz 1.2.0 from the official deb package and copied sfizz.lv2 folder in ~/.lv2. I also tried adding the ppa and installing from there.

**Comment by paulfd** [comment]
Can you link the conversations you refer to? I can reproduce actually, and this seems to be the error:
```
lilv_lib_open(): error: Failed to open library /home/paul/.lv2/sfizz.lv2/Contents/Binary/sfizz.so (/usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/paul/.lv2/sfizz.lv2/Contents/Binary/sfizz.so))
```
Apparently the freedesktop flatpak runtime used to build the Ardour flatpak ships with libc 2.33, but this one builds for 2.34 (actually my system has 2.35 but who knows...). I would assume flatpaks and plugins are quite a messy business and it showed in the past. You could try to maybe install the deb for Ubuntu 20.04 (or extract the lv2 directory from there, I did it and it works) since the libc is older on this version.

The proper way forward would be to build the plugin either against the flatpak runtime and use your technique, or preferably integrated in the flatpak subsystem. Seems like there's some support to build plugins as flatpaks: https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension

OBS also has flatpak builds: https://openbuildservice.org/2021/02/18/introducing-flatpak-builds/

If it's too complex on OBS it could be done from github. I probably won't make it a priority in the short term but feel free to pick it up (or anyone really!).

**Comment by ghost** [comment]
Thank you. I think I'll use the repo version.
